# Non-secret settings for the dev lab run. Secrets are generated by Terraform and
# stored in Secrets Manager; never put credentials here.
aws_region  = "ap-southeast-1"
environment = "dev"
owner       = "namtv"
cost_center = "do2603"
name_prefix = "do2603-namtv"
lab_id      = "do2603-namtv-day3"
expires_at  = "2026-09-28T17:00:00Z"

# Lab only: GitHub-hosted runners have dynamic IPs. API access still requires an
# IAM access entry. Conftest denies 0.0.0.0/0 for prod.
eks_public_access_cidrs = ["0.0.0.0/0"]

node_instance_types = ["t3.medium"]
node_capacity_type  = "SPOT"
node_desired_size   = 2
node_min_size       = 1
node_max_size       = 3

db_instance_class        = "db.t4g.micro"
db_multi_az              = false
db_backup_retention_days = 1
db_deletion_protection   = false
redis_num_cache_clusters = 1
