apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "insighthub.fullname" . }}-uploads
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
  annotations:
    {{- include "insighthub.checkovNamespace" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.uploads.accessMode }}]
  {{- with .Values.uploads.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.uploads.size }}
