apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insighthub.fullname" . }}-web
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    {{- include "insighthub.checkovWorkload" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "insighthub.selector" (dict "root" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insighthub.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      securityContext:
        {{- include "insighthub.podSecurityContext" (dict) | nindent 8 }}
      containers:
        - name: web
          image: {{ include "insighthub.image" .Values.images.web }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_INTERNAL_URL
              value: http://{{ include "insighthub.fullname" . }}-api:8000
          readinessProbe:
            httpGet: {path: /api/health, port: http}
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /api/health, port: http}
            initialDelaySeconds: 15
            periodSeconds: 15
          securityContext:
            {{- include "insighthub.containerSecurityContext" . | nindent 12 }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - name: next-cache
              mountPath: /app/.next/cache
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: next-cache
          emptyDir: {sizeLimit: 256Mi}
        - name: tmp
          emptyDir: {sizeLimit: 64Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insighthub.fullname" . }}-web
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    {{- include "insighthub.checkovNamespace" . | nindent 4 }}
spec:
  selector:
    {{- include "insighthub.selector" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
